<?php
function cipher_menu() {
    $items = array();
    $items['shift_cipher'] = array(
            'title' => 'Shift Cipher',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => TRUE,
            'page callback' => 'drupal_get_form',
            'page arguments' => array('shift_cipher_form'),
        );
        $items['shift_cipher_success_page'] = array(
                'title' => 'Shift Cipher Results',
                'type' => MENU_CALLBACK,
                'access callback' => TRUE,
                'page callback' => 'display_cipher_results',
            );
        return $items;
    }
