<?php
function cipher_menu() {
    $items = array();
    $items['shift_cipher'] = [
            'title' => 'A Shifty Cipher',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => TRUE,
            'page callback' => 'drupal_get_form',
            'page arguments' => array('shift_cipher_form'),
        ];
        $items['shift_cipher_success_page'] = [
                'title' => 'Shift Cipher Results',
                'type' => MENU_CALLBACK,
                'access callback' => TRUE,
                'page callback' => 'display_cipher_results',
            ];
        return $items;
    }

    // shifter number //
    function shift_cipher_form() {
        $form = [];
        $form['shifting_value'] = [
            '#title' => 'Shifting Value.',
            '#description' => t('( please input a number, this number will be the distance of moves to an encrypted letter )'),
            '#type' => 'textfield',
            '#required' => TRUE,
            '#element_validate' => ['element_validate_integer_positive'],
        ];
    // shifter direction (left - right) //
        $form['direction'] = [
            '#title' => 'Encrypt in what direction?',
            '#description' => t('( please choose a ( left ) or ( right ) direction to encrypt too )'),
            '#type' => 'textfield',
            '#required' => TRUE,
            '#element_validate' => ['element_validate_left_right'],
        ];
    // word to encrypt //
        $form['word_sentence'] = [
            '#title' => 'Enter a word or sentence.',
            '#description' => t('( this sentence will be encrypted according to your parameters )'),
            '#type' => 'textfield',
            '#required' => TRUE,
            '#element_validate' => ['element_validate_unique_characters'],
        ];

        $form['submit'] = [
            '#type' => 'submit',
            '#value' => 'ENCRYPT',
        ];
        return $form;
    }


// shifter number //
function shift_cipher_form_submit($form, &$form_state) {
    $shifting_value = $form_state['values']['shifting_value'];
    $direction = $form_state['values']['direction'];
    $word_sentence = $form_state['values']['word_sentence'];
    $_SESSION['user_input'] = $word_sentence;
    $word_sentence = str_split(strtolower($form_state['values']['word_sentence']));

    $result = [];
    $alpha = [
       'a' => 0, 'b' => 1, 'c' => 2, 'd' => 3, 'e' => 4, 'f' => 5, 'g' => 6, 'h' => 7, 'i' => 8, 'j' => 9, 'k' => 10, 'l' => 11, 'm' => 12, 'n' => 13, 'o' => 14, 'p' => 15, 'q' => 16, 'r' => 17, 's' => 18, 't' => 19,    'u' => 20, 'v' => 21, 'w' => 22, 'x' => 23, 'y' => 24, 'z' => 25
   ];

    foreach ($word_sentence as $input) {
        if ((preg_match("/[a-zA-Z]/", $input))) {

            $input = $alpha[$input];

            if ($direction == 'left') {
        $the_move = ($input - $shifting_value) % 26;
            if ($the_move < 0) {
                $the_move = $the_move + 26;
                }
            } elseif ($direction == 'right') {
                $the_move = ($input + $shifting_value) % 26;
                if ($the_move > 26) {
                    $the_move = $the_move - 26;
                    }
            }
            foreach ($alpha as $key => $value) {
                if ($the_move == $value) {
                    $the_move = $key;
                }
            }
            array_push($result, $the_move);
        } else {
            array_push($result, $input);
        }
    }

    $_SESSION['cipher_result'] = $result;
    $form_state['redirect'] = 'shift_cipher_success_page';
}

function shiftcipher_include_spaces($input) {
    return str_replace(' ', '&nbsp', $input);
}

function display_cipher_results() {
    $result = $_SESSION['cipher_result'];
    $result = implode("", $result);
    $word_sentence = $_SESSION['user_input'];
    $result = "Encryption is successful: <h2>$word_sentence</h2> has been encrypted to: <h2>$result</h2>";
    return $result;
}

// form submission //

function element_validate_left_right($element) {
    if (($element['#value'] != 'right') && ($element['#value'] != 'left')) {
        form_error($element, t('Please enter right or left for direction'));
    }
}

function element_validate_unique_characters($element) {
    if(preg_match("/[^a-zA-Z.?!', ]/", $element['#value'])) {
        form_error($element, t("Please don't use numbers or special characters!!!"));
    }
}
