<?php
function cipher_menu() {
    $items = [];
    $items['shift_cipher'] = [
            'title' => 'A Shifty Cipher',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => TRUE,
            'page callback' => 'drupal_get_form',
            'page arguments' => ['shift_cipher_form'],
        ];
        $items['shift_cipher_success_page'] =[
            'title' => 'Shift Cipher Results',
            'type' => MENU_CALLBACK,
            'access callback' => TRUE,
            'page callback' => 'display_cipher_results',
            ];
        return $items;
    }

// shifter number //
function shift_cipher_form() {
    $form = [];
    $form['shifting_value'] = [
        '#title' => 'Shifting Value',
        '#description' => t('( please input a number, this number will be the distance of moves to an encrypted letter )'),
        '#type' => 'textfield',
        '#required' => TRUE,
        '#element_validate' => ['element_validate_integer_positive'],
    ];
// shifter direction (left - right) //
    $form['direction'] = [
        '#title' => 'Encrypt in what direction?',
        '#description' => t('( please choose a ( left ) or ( right ) direction to encrypt too )'),
        '#type' => 'textfield',
        '#required' => TRUE,
        '#element_validate' => ['element_validate_left_right'],
    ];
// word to encrypt //
    $form['word'] = [
        '#title' => 'Enter a word or sentence.',
        '#description' => t('( this sentence will be encrypted according to your parameters )'),
        '#type' => 'textfield',
        '#required' => TRUE,
        '#element_validate' => ['element_validate_unique_characters'],
    ];

    $form['submit'] = [
        '#type' => 'submit',
        '#value' => 'ENCRYPT',
    ];
    return $form;
}
